[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = 'artifact_backtester_client'
version = '1.0.0'
requires-python='>=3.10.12'
readme = {file="README.md", content-type="text/markdown"}